spring.application.name=SpringBoot-CRUD

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/CoderArmySpringBootCRUD
spring.datasource.username=postgres
spring.datasource.password=06032006
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true